spring:
  application:
    name: aws-portal-api-service

  datasource:
    url: jdbc:postgresql://localhost:5432/aws_test
    username: aws
    password: aws
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
ldap:
  # Use FQDN that matches the cert's SAN/CN
  url: "ldaps://awslink.net:636"
  base: "dc=awslink,dc=net"

    # Manager/technical bind (used for lookups/searches)
  managerDn: "uid=admin,ou=people,dc=awslink,dc=net"
  managerPassword: "cv8oag4dKkXBi6AwcHtW"

  # Optional timeouts (ms)
  connectTimeout: 10000
  readTimeout: 10000